__title__ = 'requests'
__description__ = 'Send scheduled emails'
__url__ = 'https://github.com/WhiteHalmos/emailer'
__version__ = '0.3.8'
__author__ = 'Peter Wen'
__author_email__ = 'peter@whitehalmos.org'
__license__ = 'MIT'
