__title__ = 'emailer'
__description__ = 'Send scheduled emails'
__url__ = 'https://github.com/WhiteHalmos/emailer'
__author__ = 'Peter Wen'
__author_email__ = 'peter@whitehalmos.org'
__license__ = 'MIT'
__version__ = '1.0.10'
